# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jaju/github/hypar2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jaju/github/hypar2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaju/github/hypar2/CMakeFiles /home/jaju/github/hypar2/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jaju/github/hypar2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hypar

# Build rule for target.
hypar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hypar
.PHONY : hypar

# fast build rule for target.
hypar/fast:
	$(MAKE) -f src/hypar/CMakeFiles/hypar.dir/build.make src/hypar/CMakeFiles/hypar.dir/build
.PHONY : hypar/fast

#=============================================================================
# Target rules for targets named hypar-static

# Build rule for target.
hypar-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hypar-static
.PHONY : hypar-static

# fast build rule for target.
hypar-static/fast:
	$(MAKE) -f src/hypar/CMakeFiles/hypar-static.dir/build.make src/hypar/CMakeFiles/hypar-static.dir/build
.PHONY : hypar-static/fast

#=============================================================================
# Target rules for targets named charentitytest

# Build rule for target.
charentitytest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 charentitytest
.PHONY : charentitytest

# fast build rule for target.
charentitytest/fast:
	$(MAKE) -f src/test/CMakeFiles/charentitytest.dir/build.make src/test/CMakeFiles/charentitytest.dir/build
.PHONY : charentitytest/fast

#=============================================================================
# Target rules for targets named charstreamtest

# Build rule for target.
charstreamtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 charstreamtest
.PHONY : charstreamtest

# fast build rule for target.
charstreamtest/fast:
	$(MAKE) -f src/test/CMakeFiles/charstreamtest.dir/build.make src/test/CMakeFiles/charstreamtest.dir/build
.PHONY : charstreamtest/fast

#=============================================================================
# Target rules for targets named iconvtest

# Build rule for target.
iconvtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconvtest
.PHONY : iconvtest

# fast build rule for target.
iconvtest/fast:
	$(MAKE) -f src/test/CMakeFiles/iconvtest.dir/build.make src/test/CMakeFiles/iconvtest.dir/build
.PHONY : iconvtest/fast

#=============================================================================
# Target rules for targets named mmaptest

# Build rule for target.
mmaptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mmaptest
.PHONY : mmaptest

# fast build rule for target.
mmaptest/fast:
	$(MAKE) -f src/test/CMakeFiles/mmaptest.dir/build.make src/test/CMakeFiles/mmaptest.dir/build
.PHONY : mmaptest/fast

#=============================================================================
# Target rules for targets named saxtimertest

# Build rule for target.
saxtimertest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 saxtimertest
.PHONY : saxtimertest

# fast build rule for target.
saxtimertest/fast:
	$(MAKE) -f src/test/CMakeFiles/saxtimertest.dir/build.make src/test/CMakeFiles/saxtimertest.dir/build
.PHONY : saxtimertest/fast

#=============================================================================
# Target rules for targets named tokenizertest

# Build rule for target.
tokenizertest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tokenizertest
.PHONY : tokenizertest

# fast build rule for target.
tokenizertest/fast:
	$(MAKE) -f src/test/CMakeFiles/tokenizertest.dir/build.make src/test/CMakeFiles/tokenizertest.dir/build
.PHONY : tokenizertest/fast

#=============================================================================
# Target rules for targets named googleextract

# Build rule for target.
googleextract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 googleextract
.PHONY : googleextract

# fast build rule for target.
googleextract/fast:
	$(MAKE) -f src/apps/CMakeFiles/googleextract.dir/build.make src/apps/CMakeFiles/googleextract.dir/build
.PHONY : googleextract/fast

#=============================================================================
# Target rules for targets named hyhtml2text

# Build rule for target.
hyhtml2text: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyhtml2text
.PHONY : hyhtml2text

# fast build rule for target.
hyhtml2text/fast:
	$(MAKE) -f src/apps/CMakeFiles/hyhtml2text.dir/build.make src/apps/CMakeFiles/hyhtml2text.dir/build
.PHONY : hyhtml2text/fast

#=============================================================================
# Target rules for targets named hyhtmldoc

# Build rule for target.
hyhtmldoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyhtmldoc
.PHONY : hyhtmldoc

# fast build rule for target.
hyhtmldoc/fast:
	$(MAKE) -f src/apps/CMakeFiles/hyhtmldoc.dir/build.make src/apps/CMakeFiles/hyhtmldoc.dir/build
.PHONY : hyhtmldoc/fast

#=============================================================================
# Target rules for targets named hyurlextract

# Build rule for target.
hyurlextract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyurlextract
.PHONY : hyurlextract

# fast build rule for target.
hyurlextract/fast:
	$(MAKE) -f src/apps/CMakeFiles/hyurlextract.dir/build.make src/apps/CMakeFiles/hyurlextract.dir/build
.PHONY : hyurlextract/fast

#=============================================================================
# Target rules for targets named hyxmlclean

# Build rule for target.
hyxmlclean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hyxmlclean
.PHONY : hyxmlclean

# fast build rule for target.
hyxmlclean/fast:
	$(MAKE) -f src/apps/CMakeFiles/hyxmlclean.dir/build.make src/apps/CMakeFiles/hyxmlclean.dir/build
.PHONY : hyxmlclean/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... hypar"
	@echo "... hypar-static"
	@echo "... charentitytest"
	@echo "... charstreamtest"
	@echo "... iconvtest"
	@echo "... mmaptest"
	@echo "... saxtimertest"
	@echo "... tokenizertest"
	@echo "... googleextract"
	@echo "... hyhtml2text"
	@echo "... hyhtmldoc"
	@echo "... hyurlextract"
	@echo "... hyxmlclean"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

